config/routes.rb
Baku::Application.routes.draw do

  devise_for :users

  get '/about', :controller => 'pages', :action => 'about'
  get '/logs/:id(/:year)(/:month)(/:day)', :controller => 'logs', :action => 'index'

  resources :channels
  resources :servers
  resources :messages, :only => [:index, :show, :delete]
  resources :search, :only => [:index]
  resources :logs, :only => [:index]

  root 'search#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :messages
  belongs_to :server

  scope :actives, -> { where(active: true) }

  def self.get_channel(name)
    Channel.where(name: name).first
  end

  def name_without_sign
    name.delete('#')
  end

  def years
    Message.where(channel_id: id).uniq.pluck('EXTRACT(YEAR FROM created_at)')
  end

  def months(year)
    date = Date.new(year.to_i, 1, 1)
    range = date.beginning_of_year..date.end_of_year
    Message.where(channel_id: id).where(created_at: range).uniq.pluck('EXTRACT(MONTH FROM created_at)')
  end

  def days(year, month)
    date = Date.new(year.to_i, month.to_i, 1)
    range = date.beginning_of_month..date.end_of_month
    Message.where(channel_id: id).where(created_at: range).uniq.pluck('EXTRACT(DAY FROM created_at)')
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all.order(:name)
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @channel }
      else
        format.html { render action: 'new' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :server_id, :active)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.collection_select :server_id, Server.all, :id, :host %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Channels</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Server</th>
    <th>Join</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @channels.each do |channel| %>
    <tr>
      <td><%= channel.name %></td>
      <td><%= channel.server.host %></td>
      <td><%= channel.active %></td>
      <td><%= link_to 'Show', channel %></td>
      <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
      <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Server:</strong>
  <%= @channel.server.host %>
</p>

<p>
  <strong>Join:</strong>
  <%= @channel.active %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>